image: archlinux

stages:
  - test
  - deploy

cache:
  key: system-v1
  paths:
    # For some reason Gitlab CI only supports storing cache/artifacts in a path relative to the build directory
    - .pkg-cache

before_script:
  - pacman -Syu --noconfirm --noprogressbar --needed --cachedir .pkg-cache
           base-devel git gpgme protobuf pyalpm python-mysql-connector
           python-pygit2 python-srcinfo python-bleach python-markdown
           python-sqlalchemy python-alembic python-pytest python-werkzeug
           python-pytest-tap python-fastapi uvicorn nginx python-authlib
           python-itsdangerous python-httpx

test:
  stage: test
  script:
    - make -C test

deploy_dev:
  stage: deploy
  environment:
    name: dev
    url: https://aur-dev.archlinux.org
  script: "ssh deployme@aur-dev.archlinux.org"
  only:
    - develop
  resource_group: dev  # Ensure only a single deployment can run per time
  tags:
    - secure-general

deploy_production:
  stage: deploy
  environment:
    name: production
    url: https://aur.archlinux.org
  script: "ssh deployme@aur.archlinux.org"
  when: manual
  only:
    - master
  resource_group: production  # Ensure only a single deployment can run per time
  tags:
    - secure-general
